### ISSUE TITLE
Automatic deployment guide doesn't mention that the DB needs to be restored from .bak

### ISSUE THREAD

**Issue by aqyx** [microsoft/MCW-Migrating-SQL-databases-to-Azure#18]
There is no indication in the automatic deployment guide that the TailspinToys.bak file on the server C: drive must be restored before starting the HOL.

It's mentioned in the manual setup guide, but not the automatic one.

**Comment by kylebunting** [comment]
@aqyx, the steps for that are not in the HOL guide because the `TailspinToy` database should be automatically restored by the [SqlServer2008 config script](https://github.com/microsoft/MCW-Migrating-SQL-databases-to-Azure/blob/master/Hands-on%20lab/lab-files/ARM-template/configure-sqlvm.ps1), which is called by the ARM template that creates all of the lab resources. I will test the ARM template to ensure that is still working as expected.

**Comment by aqyx** [comment]
@kylebunting I didn't have same issue with my second deployment, so it may have just been a one-off issue.

**Comment by kylebunting** [comment]
@aqyx, I've just run through the lab and verified that ARM template and SqlServer2008 config script are working. Since you also did not have issues with your second deployment, I'm going to close this out as a deployment issue when you first attempted it.
