### ISSUE TITLE
Exercise 7 - Leaderboard is showing only READ_WRITE report instead of READ_ONLY

### ISSUE THREAD

**Issue by Abhishekpathania01** [microsoft/MCW-Migrating-SQL-databases-to-Azure#8]
Hi , 

After updating the connection strings ( ReadOnly at the end) it should show Read_Only data but it is showing Read_Write data only. 

Could you please check on this?

Thanks
Abhishek

**Comment by kylebunting** [comment]
@Abhishekpathania01, could you try opening the application in an Incognito or Private browser window? Sometimes things get cached in the browser. If that doesn't work, try restarting the web app in Azure.

**Comment by Abhishekpathania01** [comment]
Hi @kylebunting Thanks for your quick response. 

I tried all possibilities but still having this issue. I can share the lab environment details with you to check this quickly. Please let me know if works for you

**Comment by kylebunting** [comment]
Yes, that'll work. Please email them to me (kyle@solliance.net).

**Comment by kylebunting** [comment]
@Abhishekpathania01, the issue is that the SQL MI instance is using the General Purpose pricing tier. In order to take advantage of the Read scale-out capabilities, you need to be using the Business Critical tier of SQL MI. With Business Critical, you get a read-only secondary server as part of the high-availability features of the service level. Without that, adding `ApplicationIntent=ReadOnly` to the connection string will have no impact, and you will still be hitting the primary instance of SQL MI.

Can you try scaling up SQL MI to the Business Critical pricing tier, and retest?
